name: flutter_color_models
description: >-
  A set of classes representing the CMYK, HSI, HSL, HSP, HSB, LAB,
  Oklab, RGB, and XYZ color spaces with methods to convert colors
  between each space.
version: 1.3.3+2
homepage: https://github.com/james-alex/color_models

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  color_models: ^1.3.3
  meta: ^1.7.0
dependency_overrides:
  color_models:
    git: 
      url: https://github.com/haideralipunjabi/color_models.git
      path: color_models/
dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.21.4
